### ISSUE TITLE
0.9 build failed

### ISSUE THREAD

**Issue by eddef** [freicoin/freicoin#27]
Started to test build 0.9 as requested from jtimon to see if we can start testing. It's VERY hard when everything is as outdated as it is, i assume that builds are not that easy for you guys either and it should not end up like rocket science to make it build (several hours of searching the net for solutions)

Just to start with some.

`chainparams.cpp:327:72: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘boost::assign_detail::generic_list<int>’)`

And throws error at the end

`Makefile:816: recipe for target 'chainparams.o' failed
make[3]: *** [chainparams.o] Error 1
make[3]: Leaving directory '/home/builder/freicoin/src'
Makefile:838: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/builder/freicoin/src'
Makefile:644: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/builder/freicoin/src'
Makefile:504: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

arcarus got it failing with this 

`CXXLD freicoind
libfreicoin_wallet.a(walletdb.o): In function `SerReadWrite<CDataStream, __gmp_expr<__mpq_struct [1], __mpq_struct [1]> >':
/home/arcurus/Downloads/freicoin-0.9/src/serialize.h:782: undefined reference to `void Serialize<CDataStream>(CDataStream&, __gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&, int, int)'
/home/arcurus/Downloads/freicoin-0.9/src/serialize.h:789: undefined reference to `void Unserialize<CDataStream>(CDataStream&, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>&, int, int)'
collect2: error: ld returned 1 exit status
make[3]: *** [freicoind] Error 1
make[3]: Leaving directory `/home/arcurus/Downloads/freicoin-0.9/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/arcurus/Downloads/freicoin-0.9/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/arcurus/Downloads/freicoin-0.9/src'
make: *** [all-recursive] Error 1`

**Comment by Arcurus** [comment]
Yea would be great if we could switch to more current releases and then start testing them.

too fedde: doesn't the compiler normally say in which file and line the error was in?
the error i had is coming from serialize.h. I seems it has to do with the changed maaku added in 2013.
Maaku added these two libs:
+ gmp 5.1.2
+ mpfr 3.1.2
Maybe it helps to install these libs directly. 

What also failed is to install this lib:
sudo apt-get install libboost1.55-all-dev
Reading package lists... Done
Building dependency tree 
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libboost1.55-all-dev : Depends: libboost1.55-dev but it is not going to be installed
Depends: libboost1.55-tools-dev
Depends: libboost-atomic1.55-dev but it is not going to be installed
Depends: libboost-chrono1.55-dev but it is not going to be installed

**Comment by maaku** [comment]
I'm closing this issue because the current `master` branch has been updated to 0.9, and the build issues are as fixed as I'm willing to do so while we're in the process of rebasing to later versions. Specifically this means that while some problems related to code atrophy have been fixed, the 0.9 branch is still unlikely to build on modern build tools or recent versions of linux. However the problems which affect gitian builds have been corrected, and you can build a binary for all platforms by simply typing `cd contrib/vagrant && make all` on any supported platform.

This gitian build script creates a containerized build environment based on Ubuntu 12.04 which is able to make portable binaries without issue, with the whole process being automated. Once we bring the code base up to more recent versions of bitcoind, direct builds will once again be possible.
