### ISSUE TITLE
difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [freicoin/freicoin#33]
I saw the video on this algorithm and came to see how it was implemented.  This does not make any sense: ( [link](https://github.com/freicoin/freicoin/blob/eec192d4d5a814386fb12165c5fea703c3c90a4f/src/main.cpp#L1323) )
```
    for (; idx!=WINDOW && pitr && pitr->pprev; ++idx, pitr=pitr->pprev)
        time_delta[idx] = (int32_t)(pitr->GetBlockTime() - pitr->pprev->GetBlockTime());
    for (; idx!=WINDOW; ++idx)
        time_delta[idx] = (int32_t)nTargetSpacing;

    int64_t filtered_time = 0;
    for (idx=0; idx<WINDOW; ++idx)
        filtered_time += (int64_t)filter_coeff[idx] * (int64_t)time_delta[idx];

    return filtered_time;
```
This is supposed to be the crux of the low pass design and yet all the solvetimes assigned in the first loop are just erased with the target time of 600 seconds in the second loop.  The net effect is that the algorithm has no effect unless it needs to adjust > +/- 5% in which case it adjusts by 5%, giving rise to a persistent bad sawtooth pattern.  

![image](https://user-images.githubusercontent.com/18004719/49962676-d5a21280-fee3-11e8-8b50-d96d71e9eec2.png)

It seems like the 2nd for loop is not supposed to be there and the 3rd loop should be something like this (this doesn't work because the solvetimes (time_delta) do not have all corresponding values in the coeff lookup table) but it shows what the attempt should have been):
```
for (idx=0; idx<WINDOW; ++idx)
    filtered_time += (int64_t)filter_coeff[ time_delta[idx] ]; // and maybe *nTargetSpacing
```

The general approach seems completely wrong, so I'm not suggesting it be fixed.  It should be fixed to do  something reasonable.  [This](https://github.com/zawy12/difficulty-algorithms/issues/3#issuecomment-442129791) is what I got BTG to use.

**Comment by maaku** [comment]
> all the solvetimes assigned in the first loop are just erased with the target time of 600 seconds in the second loop

Look again. the `idx` counter is not reset across the loops. The second loop is simply filling out the array with the target interval if the first loop terminated early, a condition which only occurs in the first few blocks.

How were your charts generated?

>    for (idx=0; idx<WINDOW; ++idx)
>        filtered_time += (int64_t)filter_coeff[ time_delta[idx] ]; // and maybe *nTargetSpacing

Why? First, `time_delta[idx]` returns a solve time which isn't suitable as an index into an array--there's no way to assume you'd get a value between [0, 144), and so you'd get out of bounds memory accesses and the code would crash, or return different results on different machines.

Second, there's a type error in this code. What are you trying to achieve by looking up a value based on the actual block spacing?

**Comment by zawy12** [comment]
OK, that solves my confusion about the "erasure".  The graph is the first few thousands of blocks after the switch to this algo, not counting the ones soon after the fork.

This appears to be a assigning a filter_coeff based on window position, not the actual solvetimes.  Is that right? How does that make sense?  

```    for (idx=0; idx<WINDOW; ++idx)
        filtered_time += (int64_t)filter_coeff[idx] * (int64_t)time_delta[idx];
```

```What are you trying to achieve by looking up a value based on the actual block spacing?```
I was implying the weighting should be based on solvetime, like I thought the video said

**Comment by maaku** [comment]
> The graph is the first few thousands of blocks after the switch to this algo

What I mean is, is the graph a simulation or an actual network's block solve times? If its a simulation then there must be something wrong with your code, because I've run this exact same code in simulation and in production without observing that specific pattern.

There *is* a sawtooth-like difficulty pattern in the production freicoin network, but this is due to the effect of price combined with multi-chain hopping pools, not any details of the adjustment algorithm.

> This appears to be a assigning a filter_coeff based on window position, not the actual solvetimes. Is that right? How does that make sense?

That's just what a linear impulse response filter is:

https://en.wikipedia.org/wiki/Linear_filter

**Comment by zawy12** [comment]
The plot is Freicoin's blocks from 28500 to 40500.  With all due respect, it's a terrible algorithm.  I suspected it could not be a good idea because I was not able follow the reasoning behind the filtering or the process, and the actual results support that view.  This longer term plot starting again at 28500 is pretty bad.  
![image](https://user-images.githubusercontent.com/18004719/50007196-29f9d080-ff7e-11e8-8caf-906297b6e62b.png)

I concentrate on difficulty and keep track of the results:
[http://wordsgalore.com/diff/](http://wordsgalore.com/diff/)

I still can't understand what you're trying to do. What's the time-varying signal you're filtering? The only relevant time-varying signal in my view is hashrate which can only be estimated by solvetimes, but the estimate is so bad, it's hard to get a accurate picture of the changes.  Besides, if I know hashrate accurate enough to see the peaks, I do the opposite of a filter and raise difficulty instead of dulling the response.  

You're trying to filter the "noise" of fast solvetimes but fast solve times are not the result of an external forcing function that adds randomness to our data like 60 Hz noise can add to household devices. They are just as relevant (and as random) as the other solvetimes in trying to determine current hashrate (which is the only goal of a DA because converting hashrate to a difficulty setting straightforward).

All DAs add a weighting factor to the solvetimes or to the nBits\*solvetime value. SMA is just a "1" for all data points. LWMA gives more weight to more recent values.  EMA gives a weighting factor to only the previous solvetime based on the expected Poisson distribution. Both of these are also used as stock-price estimators.  Digishield gives weight to only the most recent 17 solvetimes, but reduces their effect to only 0.25 of what an N=17 SMA would do.  (Digishield actually only starts its N=17 sample at the MTP, about 6 blocks in the past, so it also has more-than-necessary oscillations and will not perform well if a coin gets in a bad nicehash situation, otherwise it's one of the top 3 algos.)

LWMA, EMA, and Digishield (DGW is just a N=24 simple moving average in deep disguise)  base their weighting on the most recent solvetimes but Freicoin is just giving weight to blocks near 72 blocks in the past so it's always trying to merely estimate the hashrate as it was half a day ago (assuming I'm reading the code correctly). This, combined with only taking the most recent nBits value into account (instead of the ones near the 72 point in the past) is causing a 1-day delay in reaching what it should have been half a day in the past.  Miner motivation combined with the delay is what causes the peaks and valleys to be substantial.

**Comment by maaku** [comment]
Well, with respect it is a standard algorithm from the control theory literature. We can debate whether the category of linear finite impulse response filters was the correct choice, or whether the meta-parameters selected (144 block window, cutoff frequency, etc.) were optimal, but in fact there is underlying theory showing the Parks–McClellan filter design used is optimal under the design requirements chosen.

And the design *is* critically damped against a square-wave impulse response, meaning that it provides the optimal response possible under the design constraints. The sawtooth pattern you are seeing the the actual block frequency of the freicoin chain is due to hash rate not being an independent variable but in fact being a function of the relative price of freicoin to bitcoin vs. difficulty. This pragmatic reality would affect any choice of difficulty adjustment algorithm so long as the proof of work is shared but not merge mined.

Having an algorithm that works quickly in simulation is not sufficient. This is an adversarial environment where you must also show that it is not possible for malicious miners, whether a minority or majority of the hash rate working in collusion or according to predicted game theoretic outcomes, cannot advantageously affect the difficulty adjustment by manipulating timestamps they control. It *is* possible to prove game theoretic properties of a linear finite impulse response filter, like the one used here. There are a few other choices of algorithm that would provide similar guarantees. But the stateful infinite impulse response filters like you describe explicitly *do not* yield a theoretical framework describing them that could be used to prove their properties in an adversarial environment.

In other words, an algorithm like Digishield works when you assume the miners are honest. But no simulation can possibly show all the various ways miners working together or separately can manipulate the chain's view of time in such a way as to gain advantage, and FIR filters provide guaranteed limits on that advantage which more ad-hoc solutions do not.

I appreciate the work that you've put into researching this very complex topic, and I do think that there is unfinished business with respect to designing a better, more responsive difficulty adjustment filter. But for the moment I am closing this issue as 'wont-fix' because for our project at least the category of filters you describe are not optimal. If we change the difficulty adjustment algorithm, which we are likely to do with the deployment of forward blocks, it'll likely be another linear impulse response filter, perhaps with evolutionary selected meta-parameters, or filter based on Bessel functions instead of the Chebyshev polynomials used in Parks-McClellan. I'm open to other ideas, but only if there's a solid theoretical backing from which we can guarantee runtime properties.

(Aside: to prime your intuition for how a linear filter works, note that it is performing the following calculation, where `x_1` through `x_4` is the reported solve time between consecutive blocks:

    FIR(xs) = a_1*x_1 + a_2*x_2 + ... + a_144*x_144

Now a low-pass filter like we want would ignore short-duration variations due to the randomness of the Poisson distribution, while giving more weight to patterns developing over time. If you look at a fixed window, for the purposes of an example let's say 4 blocks, you can break out all the possible durations and weight them separately:

    FIR_1(xs) = a_1*(x_2 - x_1) + a_2*(x_3 - x_2) + a_3*(x_4 - x_3)
    FIR_2(xs) = b_1*(x_3 - x_1) + b_2*(x_4 - x_2)
    FIR_3(xs) = c_1*(x_4 - x_1)
    FIR(xs) = FIR_1(xs) + FIR_2(xs) + FIR_3(xs)

In other words, by assigning smaller values to the `a_X` constants and larger values to the `b_X` and `c_X` constants we can make the block-to-block differences matter less than the overall trend, e.g. a low-pass filter. Note that you can re-arrange these into the standard form of a linear equation:

    FIR_1(xs) = (-a_1)*x_1 + (a_1-a_2)*x_2 + (a_2-a_3)*x_3 + (a_3-a_4)*x_4
    FIR_2(xs) = (-b_1)*x_1 +    (-b_2)*x_2 +     (b_1)*x_3 +     (b_2)*x_4
    FIR_3(xs) = (-c_1)*x_1 +         0*x_2 +         0*x_3 +     (c_1)*x_4

And combined:

    FIR(xs) = (-a_1-b_1-c_1)*x_1 + (a_1-a_2-b_2)*x_2 + (a_2-a_3+b_1)*x_3 + (a_3-a_4+b_2+c_1)*x_4

Let's call these weights ω:

    ω_1 = -a_1       - b_1 - c_1
    ω_2 =  a_1 - a_2 - b_2
    ω_3 =  a_2 - a_3 + b_1
    ω_4 =  a_3 - a_4 + b_2 + c_1

So:

    FIR(xs) = ω_1*x_1 + ω_2*x_2 + ω_3*x_3 + ω_4*x_4

And if we recall that `x_1` is the time between the first and second most recent blocks, `x_2` the time between the second and third most recent blocks, etc., then we get the following:

    FIR(xs) = ω_1*(t_1-t_0) + ω_2*(t_2-t_1) + ω_3*(t_3-t_2) + ω_4*(t_4-t_3)

This is what the Freicoin difficulty adjustment code is doing, with weight values selected by the Parks-McClellen algorithm.)

**Comment by zawy12** [comment]
The charts are live coin data, not simulations.  It's very difficult to find difficulty plots for coins that have done this bad.   It's currently stuck because of the algorithm, not because of any hashrate problem.  The last 144 blocks show how badly it it is performing even when not counting the last few blocks: the 144-block average solvetime was 25x higher than target, getting longer in more recent blocks, and yet difficulty continually rose and is currently over 2x higher than it was 144 blocks in the past.  

Thanks for the thorough explanation.  You're using solvetimes instead of something like voltage as a signal, and block number in place of a time axis. A time-based voltage has a linear and high correlation to nearby voltages.  Solvetimes jump from one to the next randomly with almost no correlation.  The StdDev of the solvetimes are 10x higher than a 10% hashrate change. 

 You called this a long term trend
```FIR_3(xs) = c_1*(x_4 - x_1)```
but the difference between first and last solvetimes is not meaningful.  

The relevant signal here is hashrate and it's not noisy, so you do not apply a low pass filter directly to it.  But the solvetimes are the noisy window we have to look through.    A simple moving average is a low pass filter.  The longer the window, the more it filters.  A different type of low-pass filter applicable here is to limit the adjustment in whatever DA algorithm is used.  For example, the following is a really good DA:
```nextTarget = previousSolvetime > ln(2)*600 ? prevTarget*1.02 : prevTarget/1.02;```
The median solvetime of a Poisson process is ln(2) = 0.693 of target solvetime, and it just jumps up or down 2% depending if it's above or below that value.   I'm describing this to emphasize the Poisson process here is not "noisy" in the traditional sense (e.g. like 60 Hz) and can be dealt with more simply (such as not requiring a complex filter or ever looking at more than 1 block to work correctly).  Here it is compared to other algorithms under 5x on-off mining conditions (simulations). It looks a lot better than the others, but note that it it's avg solvetime is higher from the attacks which prevents it from falling back down to trigger a new low-difficulty-motivated attack. 

![image](https://user-images.githubusercontent.com/18004719/50024128-67c31d00-ffaf-11e8-9d53-9591009c2754.png)

But it should not be used because a big miner like > 25% can make all his solvetimes 1 second above the cutoff to drive difficulty lower than it should be. Worse, a selfish mine with > 51% hashrate could repeat a sequence of solvetimes like this 601, 601, 601, 601, 0 to get unlimited blocks in a very short time.

**Comment by freicoin** [comment]
> On Dec 14, 2018, at 11:52 AM, zawy12 <notifications@github.com> wrote:
> You called this a long term trend
> 
> FIR_3(xs) = c_1*(x_4 - x_1)
> but the difference between first and last solvetimes is not meaningful.
> 
Whoops, my writeup was in error. This should be the difference between the first and the fourth block time looking back, not the difference in solve times between the first and fourth intervals. My bad.
> The relevant signal here is hashrate and it's not noisy, so you do not apply a low pass filter directly to it. But the solvetimes are the noisy window we have to look through. A simple moving average is a low pass filter. The longer the window, the more it filters. A different type of low-pass filter applicable here is to limit the adjustment in whatever DA algorithm is used. For example, the following is a really good DA:
> nextTarget = previousSolvetime > ln(2)*600 ? prevTarget*1.02 : prevTarget/1.02;
> The median solvetime of a Poisson process is ln(2) = 0.693 of target solvetime, and it just jumps up or down 2% depending if it's above or below that value.
> 
So, as a miner, I simply set the block time, which I have control over, to `ln(2)*600=416s` more than the previous block time. Every single round reduces difficulty until blocks are coming faster than 416 seconds apart. Now you’ve effectively reduced the block time by 30% and eliminated any responsiveness to hash rate at all since the timestamps no longer correspond to reality.

You’re not thinking adversarially.

**Comment by zawy12** [comment]
Right, I just edited my previous post to describe how a big miner could manipulate difficulty. For example, a 20% miner will be able to make 10% of the blocks above the cutoff when they should have been below the cut-off, so it would result in the average difficulty being a max 10% lower than it should be. But his assignments will make more of the subsequent timestamps go the other way, so the max effect he could have might be 5% lower.  But when his other 10% would have naturally lowered difficulty anyway with longer solvetimes, he can make them barely longer solvetimes to increase the chances the next honest timestamp assignment will also appear longer, so maybe 10% lower difficulty is about right. The real danger is from > 51% miners who do a selfish mine and get unlimited blocks.

**Comment by zawy12** [comment]
If you correct it I think you'll find the algorithm has an error and that when you simplify it and make it more aggressive (allowing only the lowest frequency through) it will simplify to a simple moving average.  It will not simplify exactly but to something less accurate because only the previous nBits is being taken into account.

**Comment by zawy12** [comment]
Correction. As the final equation stands, it's going to be more like Digishield.  Digishield is 
``` bnNew = avg(17 nBits) * [3+avg(17 solvetimes)/T] / 4```
where T = target solvetime.  The general speed of response is about like a simple moving average with N=17\*4 = 68 like this
```bnNew = avg(68 nBits) * avg(68 solvetimes)/T```
Freicoin (not counting the limits) is approximately 
```bnNew = previous_nBits * 10 / [11 - avg(Filtered STs)/T ] ```
So instead of adding a solvetime/T ratio in numerator, it is subtracting it in the denominator, which may turn out fairly close to being the same, especially since the 10 and 11 make the ratio stay close to 1.  Using the previous instead of avg nBits will cause some error.  To be as fast as Digishield would require the number of most recent solvetimes averaged to be N=\~6 because the "dilution" or "tempering" factor is 11 instead of 4, i.e.  11\*6 =\~ 4\*17.
